[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301


[build]
  command = "npm run build:netlify"
  publish = "build/client"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=6144"

[functions]
  included_files = ["app/client/assets/books/seo-summaries/book-seo-summaries.json"]

[dev]
  command = "react-router dev"
