import * as React from "react";

const styles: Record<string, React.CSSProperties> = {
  page: {
    background: "transparent",
    color: "#111317",
    fontFamily:
      "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
    margin: 0,
  },
  wrap: {
    boxSizing: "border-box",
    maxWidth: 1120,
    margin: "0 auto",
    padding: "8px clamp(16px, 3vw, 32px) 36px",
  },

  breadcrumb: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 18,
    fontSize: "1.05rem",
  },
  breadcrumbLink: {
    color: "inherit",
    textDecoration: "underline",
  },
  breadcrumbSep: { color: "#111317" },
  breadcrumbCurrent: { fontWeight: 700 },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 0",
    borderBottom: 0,
  },
  brand: { display: "flex", alignItems: "center", gap: 12 },
  logo: {
    width: 44,
    height: 44,
    border: 0,
    borderRadius: 10,
    background: "#fff",
    position: "relative",
  },
  siteTitle: { fontWeight: 800, letterSpacing: 0.3, fontSize: "1.15rem" },
  tagline: { color: "#5a616c", fontSize: ".95rem" },

  h1: {
    fontSize: "clamp(2.25rem, 2.2vw + 1rem, 4rem)",
    lineHeight: 1.15,
    margin: 0,
    color: "#08324f",
    fontWeight: 900,
  },
  lead: {
    marginTop: 12,
    color: "#334155",
    fontSize: "1.08rem",
    lineHeight: 1.7,
    maxWidth: 760,
  },
  card: {
    background: "#fffdf8",
    border: 0,
    borderRadius: 16,
  },
  cardPad: { padding: 16 },
  section: { padding: "8px 0 24px" },
  sectionTitle: { fontSize: "1.35rem", margin: "0 0 12px" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  label: { fontSize: ".9rem", color: "#5a616c" },
  textarea: {
    width: "100%",
    minHeight: 140,
    padding: 12,
    border: 0,
    borderRadius: 10,
    background: "#fffdf8",
    color: "#111317",
    font: '500 0.98rem/1.45 ui-monospace, SFMono-Regular, Menlo, Consolas, "Courier New"',
  },
  input: {
    width: "100%",
    minHeight: 40,
    padding: 10,
    border: 0,
    borderRadius: 10,
    background: "#fffdf8",
    color: "#111317",
    font: '600 0.98rem/1 ui-monospace, SFMono-Regular, Menlo, Consolas, "Courier New"',
  },
  controls: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 10,
  },
  btnPrimary: {
    border: 0,
    background: "#0b2447",
    color: "#fff",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 800,
    cursor: "pointer",
  },
  btnSecondary: {
    border: 0,
    background: "#fffdf8",
    color: "#0b2447",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 800,
    cursor: "pointer",
  },
  btnGhost: {
    border: 0,
    background: "#fffaf2",
    color: "#111317",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 800,
    cursor: "pointer",
  },
  note: { color: "#5a616c", fontSize: ".9rem" },
  footer: {
    color: "#5a616c",
    fontSize: ".9rem",
    textAlign: "center",
    padding: "28px 0",
  },
};

export default styles;
