import * as React from "react";

const styles: Record<string, React.CSSProperties> = {
  page: {
    background: "transparent",
    color: "var(--mw-text)",
    fontFamily:
      'var(--font-body, "DM Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif)',
    margin: 0,
  },
  wrap: {
    boxSizing: "border-box",
    maxWidth: 1120,
    margin: "0 auto",
    padding: "8px clamp(16px, 3vw, 32px) 36px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 0",
    borderBottom: 0,
  },
  brand: { display: "flex", alignItems: "center", gap: 12 },
  logo: {
    width: 44,
    height: 44,
    border: 0,
    borderRadius: 10,
    background: "var(--mw-surface-elevated)",
    position: "relative",
  },
  siteTitle: { fontWeight: 800, letterSpacing: 0.3, fontSize: "1.15rem" },
  tagline: { color: "var(--mw-text-faint)", fontSize: ".95rem" },

  h1: {
    fontSize: "clamp(2.25rem, 2.2vw + 1rem, 4rem)",
    lineHeight: 1.15,
    margin: 0,
    color: "var(--mw-heading-object)",
    fontWeight: 900,
  },
  lead: {
    marginTop: 12,
    color: "var(--mw-text-muted)",
    fontSize: "1.08rem",
    lineHeight: 1.7,
    maxWidth: 760,
  },
  card: {
    background: "var(--mw-surface)",
    border: 0,
    borderRadius: 16,
  },
  cardPad: { padding: 16 },
  section: { padding: "8px 0 24px" },
  sectionTitle: { fontSize: "1.35rem", margin: "0 0 12px" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  label: { fontSize: ".9rem", color: "var(--mw-text-faint)" },
  textarea: {
    width: "100%",
    minHeight: 140,
    padding: 12,
    border: 0,
    borderRadius: 10,
    background: "var(--mw-surface)",
    color: "var(--mw-text)",
    font: "500 0.98rem/1.45 var(--font-mono)",
    outline: "none",
    boxShadow: "none",
  },
  input: {
    width: "100%",
    minHeight: 40,
    padding: 10,
    border: 0,
    borderRadius: 10,
    background: "var(--mw-surface)",
    color: "var(--mw-text)",
    font: "600 0.98rem/1 var(--font-mono)",
    outline: "none",
    boxShadow: "none",
  },
  controls: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 10,
  },
  btnPrimary: {
    border: 0,
    background: "var(--mw-heading-object)",
    color: "var(--mw-text-inverse)",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 800,
    cursor: "pointer",
  },
  btnSecondary: {
    border: 0,
    background: "var(--mw-surface)",
    color: "var(--mw-heading-object)",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 800,
    cursor: "pointer",
  },
  btnGhost: {
    border: 0,
    background: "var(--mw-surface-muted)",
    color: "var(--mw-text)",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 800,
    cursor: "pointer",
  },
  note: { color: "var(--mw-text-faint)", fontSize: ".9rem" },
  footer: {
    color: "var(--mw-text-faint)",
    fontSize: ".9rem",
    textAlign: "center",
    padding: "28px 0",
  },
};

export default styles;
