import { type RouteConfig, index, route } from "@react-router/dev/routes";
import { ROUTES, routeSlug } from "./client/data/routes";

export default [
  // Canonical translator
  index("routes/home.tsx"),

  // MVP feature routes
  route("audio", "routes/audio.tsx"),
  route("morse-code-audio-decoder", "routes/morse-code-audio-decoder.tsx"),
  route("practice", "routes/practice.tsx"),
  route("typing", "routes/typing.tsx"),
  route("how-to-use", "routes/how-to-use.tsx"),
  route("dictionary", "routes/dictionary.tsx"),
  route("about", "routes/about.tsx"),
  route("name-to-morse-code", "routes/name-to-morse-code.tsx"),
  route("morse-code-encoder", "routes/morse-code-encoder.tsx"),
  route("morse-code-decoder", "routes/morse-code-decoder.tsx"),
  route("morse-code-reader", "routes/morse-code-reader.tsx"),
  route(
    "the-quick-brown-fox-morse-code",
    "routes/the-quick-brown-fox-morse-code.tsx",
  ),
  route("morse-code-word-separator", "routes/morse-code-word-separator.tsx"),
  route("morse-code-words", "routes/morse-code-words.tsx"),
  route("morse-code-chart", "routes/morse-code-chart.tsx"),
  route("morse-code-alphabet", "routes/morse-code-alphabet.tsx"),
  route(routeSlug(ROUTES.lettersAlias), "routes/morse-code-letters.tsx"),
  route("a-in-morse-code", "routes/a-in-morse-code.tsx"),
  route("b-in-morse-code", "routes/b-in-morse-code.tsx"),
  route("c-in-morse-code", "routes/c-in-morse-code.tsx"),
  route("d-in-morse-code", "routes/d-in-morse-code.tsx"),
  route("e-in-morse-code", "routes/e-in-morse-code.tsx"),
  route("f-in-morse-code", "routes/f-in-morse-code.tsx"),
  route("g-in-morse-code", "routes/g-in-morse-code.tsx"),
  route("h-in-morse-code", "routes/h-in-morse-code.tsx"),
  route("i-in-morse-code", "routes/i-in-morse-code.tsx"),
  route("j-in-morse-code", "routes/j-in-morse-code.tsx"),
  route("k-in-morse-code", "routes/k-in-morse-code.tsx"),
  route("l-in-morse-code", "routes/l-in-morse-code.tsx"),
  route("m-in-morse-code", "routes/m-in-morse-code.tsx"),
  route("n-in-morse-code", "routes/n-in-morse-code.tsx"),
  route("o-in-morse-code", "routes/o-in-morse-code.tsx"),
  route("p-in-morse-code", "routes/p-in-morse-code.tsx"),
  route("q-in-morse-code", "routes/q-in-morse-code.tsx"),
  route("r-in-morse-code", "routes/r-in-morse-code.tsx"),
  route("s-in-morse-code", "routes/s-in-morse-code.tsx"),
  route("t-in-morse-code", "routes/t-in-morse-code.tsx"),
  route("u-in-morse-code", "routes/u-in-morse-code.tsx"),
  route("v-in-morse-code", "routes/v-in-morse-code.tsx"),
  route("w-in-morse-code", "routes/w-in-morse-code.tsx"),
  route("x-in-morse-code", "routes/x-in-morse-code.tsx"),
  route("y-in-morse-code", "routes/y-in-morse-code.tsx"),
  route("z-in-morse-code", "routes/z-in-morse-code.tsx"),
  route("morse-code-numbers", "routes/morse-code-numbers.tsx"),
  route("0-in-morse-code", "routes/0-in-morse-code.tsx"),
  route("1-in-morse-code", "routes/1-in-morse-code.tsx"),
  route("2-in-morse-code", "routes/2-in-morse-code.tsx"),
  route("3-in-morse-code", "routes/3-in-morse-code.tsx"),
  route("4-in-morse-code", "routes/4-in-morse-code.tsx"),
  route("5-in-morse-code", "routes/5-in-morse-code.tsx"),
  route("6-in-morse-code", "routes/6-in-morse-code.tsx"),
  route("7-in-morse-code", "routes/7-in-morse-code.tsx"),
  route("8-in-morse-code", "routes/8-in-morse-code.tsx"),
  route("9-in-morse-code", "routes/9-in-morse-code.tsx"),
  route("morse-code-printable-chart", "routes/morse-code-printable-chart.tsx"),
  route(
    "morse-code-international-translator",
    "routes/morse-code-international-translator.tsx",
  ),
  route("morse-code-sos", "routes/morse-code-sos.tsx"),
  route("morse-code-sentence-practice", "routes/morse-code-sentence-practice.tsx"),
  route("learn-morse-code", "routes/learn-morse-code.tsx"),
  route("morse-code-timing", "routes/morse-code-timing.tsx"),
  route("farnsworth-timing", "routes/farnsworth-timing.tsx"),
  route("morse-code-word-trainer", "routes/morse-code-word-trainer.tsx"),
  route("sources", "routes/sources.tsx"),
  route("morse-code-prosigns", "routes/morse-code-prosigns.tsx"),
  route("morse-code-q-codes", "routes/morse-code-q-codes.tsx"),
  route("morse-code-punctuation", "routes/morse-code-punctuation.tsx"),
  route("morse-code-practice-plan", "routes/morse-code-practice-plan.tsx"),
  route("morse-code-test", "routes/morse-code-test.tsx"),
  route(
    "international-morse-code-reference",
    "routes/international-morse-code-reference.tsx",
  ),
  route("morse-code-audio-practice", "routes/morse-code-audio-practice.tsx"),
  route(
    "morse-code-word-search-builder",
    "routes/morse-code-word-search-builder.tsx",
  ),
  route("morse-code-visual-practice", "routes/morse-code-visual-practice.tsx"),
  route("morse-code-audio-quiz", "routes/morse-code-audio-quiz.tsx"),
  route("morse-code-visual-quiz", "routes/morse-code-visual-quiz.tsx"),
  route(routeSlug(ROUTES.visualQuizTypoAlias), "routes/morse-code-vidual-quiz.tsx"),
  route("morse-code-sound-generator", "routes/morse-code-sound-generator.tsx"),
  route(
    "morse-code-mp3-generator",
    "routes/morse-code-mp3-generator.tsx",
  ),
  route("morse-code-book-translator", "routes/morse-code-book-translator.tsx"),
  route("morse-code-printable-pages", "routes/morse-code-printable-pages.tsx"),
  route("morse-code-books", "routes/morse-code-books.tsx"),
  route("morse-code-books/:slug/print", "routes/morse-code-books.$slug.print.tsx"),
  route("morse-code-books/:slug", "routes/morse-code-books.$slug.tsx"),
  route("morse-code-audiobooks", "routes/morse-code-audiobooks.tsx"),
  route("morse-code-audiobooks/:slug", "routes/morse-code-audiobooks.$slug.tsx"),
  route("morse-code-by-language", "routes/morse-code-by-language.tsx"),
  route(
    "morse-code-by-language/japanese",
    "routes/morse-code-by-language/japanese.tsx",
  ),
  route(
    "morse-code-by-language/russian",
    "routes/morse-code-by-language/russian.tsx",
  ),
  route(
    "morse-code-by-language/greek",
    "routes/morse-code-by-language/greek.tsx",
  ),
  route(
    "morse-book-content/books/:slug",
    "routes/morse-book-content.books.$slug.tsx",
  ),
  route("morse-code-video-generator", "routes/morse-code-video-generator.tsx"),
  route("how-to-read-morse-code", "routes/how-to-read-morse-code.tsx"),
  route("how-to-write-in-morse-code", "routes/how-to-write-in-morse-code.tsx"),
  route("how-to-type-in-morse-code", "routes/how-to-type-in-morse-code.tsx"),
  route("copy-and-paste-morse-code", "routes/copy-and-paste-morse-code.tsx"),
  route("morse-code-without-spaces", "routes/morse-code-without-spaces.tsx"),
  route(
    "how-to-separate-words-in-morse-code",
    "routes/how-to-separate-words-in-morse-code.tsx",
  ),
  route("i-love-you-in-morse-code", "routes/i-love-you-in-morse-code.tsx"),
  route("cq-in-morse-code", "routes/cq-in-morse-code.tsx"),
  route("hello-in-morse-code", "routes/hello-in-morse-code.tsx"),
  route("hi-in-morse-code", "routes/hi-in-morse-code.tsx"),
  route("help-in-morse-code", "routes/help-in-morse-code.tsx"),
  route("help-me-in-morse-code", "routes/help-me-in-morse-code.tsx"),
  route("yes-in-morse-code", "routes/yes-in-morse-code.tsx"),
  route("no-in-morse-code", "routes/no-in-morse-code.tsx"),
  route("ok-in-morse-code", "routes/ok-in-morse-code.tsx"),
  route("sorry-in-morse-code", "routes/sorry-in-morse-code.tsx"),
  route("love-in-morse-code", "routes/love-in-morse-code.tsx"),
  route("hello-world-in-morse-code", "routes/hello-world-in-morse-code.tsx"),
  route("test-in-morse-code", "routes/test-in-morse-code.tsx"),
  route("question-mark-in-morse-code", "routes/question-mark-in-morse-code.tsx"),
  route("at-sign-in-morse-code", "routes/at-sign-in-morse-code.tsx"),
  route("space-in-morse-code", "routes/space-in-morse-code.tsx"),
  route("slash-in-morse-code", "routes/slash-in-morse-code.tsx"),
  route("period-in-morse-code", "routes/period-in-morse-code.tsx"),
  route("comma-in-morse-code", "routes/comma-in-morse-code.tsx"),
  route(
    "exclamation-mark-in-morse-code",
    "routes/exclamation-mark-in-morse-code.tsx",
  ),
  route("apostrophe-in-morse-code", "routes/apostrophe-in-morse-code.tsx"),
  route("hyphen-in-morse-code", "routes/hyphen-in-morse-code.tsx"),
  route("colon-in-morse-code", "routes/colon-in-morse-code.tsx"),
  route("semicolon-in-morse-code", "routes/semicolon-in-morse-code.tsx"),
  route("equals-sign-in-morse-code", "routes/equals-sign-in-morse-code.tsx"),
  route("plus-sign-in-morse-code", "routes/plus-sign-in-morse-code.tsx"),
  route(
    "quotation-mark-in-morse-code",
    "routes/quotation-mark-in-morse-code.tsx",
  ),
  route("parentheses-in-morse-code", "routes/parentheses-in-morse-code.tsx"),
  route("ampersand-in-morse-code", "routes/ampersand-in-morse-code.tsx"),
  route("underscore-in-morse-code", "routes/underscore-in-morse-code.tsx"),
  route("contact", "routes/contact.tsx"),
  route("sitemap", "routes/sitemap.tsx"),

  // Redirects for old URLs. Ignore these routes
  route(routeSlug(ROUTES.translatorAlias), "routes/morse-code-translator.tsx"),
  route(routeSlug(ROUTES.dictionaryAlias), "routes/morse-code-dictionary.tsx"),
  route(routeSlug(ROUTES.wordGameAlias), "routes/morse-code-word-game.tsx"),
  route(routeSlug(ROUTES.audioGeneratorAlias), "routes/morse-code-audio-generator.tsx"),
  route(routeSlug(ROUTES.textToMorseAlias), "routes/text-to-morse-code.tsx"),
  route(routeSlug(ROUTES.morseToTextAlias), "routes/morse-to-text.tsx"),
  route(routeSlug(ROUTES.audioToMorseAlias), "routes/audio-to-morse-code.tsx"),
  route(routeSlug(ROUTES.audioToTextAlias), "routes/morse-code-audio-to-text.tsx"),
  route(routeSlug(ROUTES.soundToTextAlias), "routes/morse-code-sound-to-text.tsx"),
  route(routeSlug(ROUTES.fromAudioAlias), "routes/morse-code-from-audio.tsx"),
  route(routeSlug(ROUTES.translateAudioAlias), "routes/translate-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.realtimeAudioDecoderAlias), "routes/real-time-morse-code-decoder.tsx"),
  route(routeSlug(ROUTES.mp3AudioDecoderAlias), "routes/mp3-morse-code-decoder.tsx"),
  route(routeSlug(ROUTES.wavAudioDecoderAlias), "routes/wav-morse-code-decoder.tsx"),
  route(routeSlug(ROUTES.internationalChartAlias), "routes/international-morse-code-chart.tsx"),
  route(routeSlug(ROUTES.chartAz09Alias), "routes/morse-code-chart-a-z-0-9.tsx"),
  route(routeSlug(ROUTES.alphabetChartAlias), "routes/morse-code-alphabet-chart.tsx"),
  route(routeSlug(ROUTES.practiceTestAlias), "routes/morse-code-practice-test.tsx"),
  route(routeSlug(ROUTES.listeningTestAlias), "routes/morse-code-listening-test.tsx"),
  route(routeSlug(ROUTES.typingTestAlias), "routes/morse-code-typing-test.tsx"),
  route(routeSlug(ROUTES.speedTestAlias), "routes/morse-code-speed-test.tsx"),
  route(routeSlug(ROUTES.morseTypeTestAlias), "routes/morse-type-test.tsx"),
  route(routeSlug(ROUTES.testsAlias), "routes/morse-code-tests.tsx"),
  route(routeSlug(ROUTES.testOnlineAlias), "routes/morse-code-test-online.tsx"),
  route(routeSlug(ROUTES.morseReaderAlias), "routes/morse-reader.tsx"),
  route(routeSlug(ROUTES.readMorseAlias), "routes/read-morse-code.tsx"),
  route(routeSlug(ROUTES.morseToEnglishAlias), "routes/morse-to-english.tsx"),
  route(routeSlug(ROUTES.morseCodeToEnglishAlias), "routes/morse-code-to-english.tsx"),
  route(routeSlug(ROUTES.textToMorseMp3Alias), "routes/text-to-morse-code-mp3.tsx"),
  route(routeSlug(ROUTES.morseToMp3Alias), "routes/morse-to-mp3.tsx"),
  route(routeSlug(ROUTES.morseCodeToMp3Alias), "routes/morse-code-to-mp3.tsx"),
  route(routeSlug(ROUTES.textToMorseMp3ShortAlias), "routes/text-to-morse-mp3.tsx"),
  route(
    routeSlug(ROUTES.translatorAudioMp3Alias),
    "routes/morse-code-translator-audio-mp3.tsx",
  ),
  route(routeSlug(ROUTES.textToMorseVideoAlias), "routes/text-to-morse-code-video.tsx"),
  route(routeSlug(ROUTES.ebookTranslatorAlias), "routes/morse-code-ebook-translator.tsx"),

  // Misc / legal
  route("misc", "routes/misc/misc.tsx", [
    route("cookies-policy", "routes/misc/misc.cookies-policy.tsx"),
    route("privacy-policy", "routes/misc/misc.privacy-policy.tsx"),
    route("socials", "routes/misc/misc.socials.tsx"),
    route("terms-of-service", "routes/misc/misc.terms-of-service.tsx"),
  ]),
] satisfies RouteConfig;
