import { type RouteConfig, index, route } from "@react-router/dev/routes";
import { ROUTES, routeSlug } from "./client/data/routes";

export default [
  // Canonical translator
  index("routes/home.tsx"),
  route("llms.txt", "routes/llms.ts"),
  route("llms-full.txt", "routes/llms-full.ts"),

  // MVP feature routes
  route("audio", "routes/audio.tsx"),
  route("morse-code-audio-decoder", "routes/morse-code-audio-decoder.tsx"),
  route("practice", "routes/practice.tsx"),
  route("typing", "routes/typing.tsx"),
  route("how-to-use", "routes/how-to-use.tsx"),
  route("dictionary", "routes/dictionary.tsx"),
  route("about", "routes/about.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("cookies", "routes/cookies.tsx"),
  route("name-to-morse-code", "routes/name-to-morse-code.tsx"),
  route("morse-code-encoder", "routes/morse-code-encoder.tsx"),
  route("morse-code-decoder", "routes/morse-code-decoder.tsx"),
  route("morse-code-reader", "routes/morse-code-reader.tsx"),
  route(
    "the-quick-brown-fox-morse-code",
    "routes/the-quick-brown-fox-morse-code.tsx",
  ),
  route("morse-code-word-separator", "routes/morse-code-word-separator.tsx"),
  route("morse-code-words", "routes/morse-code-words.tsx"),
  route("morse-code-chart", "routes/morse-code-chart.tsx"),
  route("morse-code-alphabet", "routes/morse-code-alphabet.tsx"),
  route(routeSlug(ROUTES.lettersAlias), "routes/morse-code-letters.tsx"),
  route("a-in-morse-code", "routes/a-in-morse-code.tsx"),
  route("b-in-morse-code", "routes/b-in-morse-code.tsx"),
  route("c-in-morse-code", "routes/c-in-morse-code.tsx"),
  route("d-in-morse-code", "routes/d-in-morse-code.tsx"),
  route("e-in-morse-code", "routes/e-in-morse-code.tsx"),
  route("f-in-morse-code", "routes/f-in-morse-code.tsx"),
  route("g-in-morse-code", "routes/g-in-morse-code.tsx"),
  route("h-in-morse-code", "routes/h-in-morse-code.tsx"),
  route("i-in-morse-code", "routes/i-in-morse-code.tsx"),
  route("j-in-morse-code", "routes/j-in-morse-code.tsx"),
  route("k-in-morse-code", "routes/k-in-morse-code.tsx"),
  route("l-in-morse-code", "routes/l-in-morse-code.tsx"),
  route("m-in-morse-code", "routes/m-in-morse-code.tsx"),
  route("n-in-morse-code", "routes/n-in-morse-code.tsx"),
  route("o-in-morse-code", "routes/o-in-morse-code.tsx"),
  route("p-in-morse-code", "routes/p-in-morse-code.tsx"),
  route("q-in-morse-code", "routes/q-in-morse-code.tsx"),
  route("r-in-morse-code", "routes/r-in-morse-code.tsx"),
  route("s-in-morse-code", "routes/s-in-morse-code.tsx"),
  route("t-in-morse-code", "routes/t-in-morse-code.tsx"),
  route("u-in-morse-code", "routes/u-in-morse-code.tsx"),
  route("v-in-morse-code", "routes/v-in-morse-code.tsx"),
  route("w-in-morse-code", "routes/w-in-morse-code.tsx"),
  route("x-in-morse-code", "routes/x-in-morse-code.tsx"),
  route("y-in-morse-code", "routes/y-in-morse-code.tsx"),
  route("z-in-morse-code", "routes/z-in-morse-code.tsx"),
  route("morse-code-numbers", "routes/morse-code-numbers.tsx"),
  route("0-in-morse-code", "routes/0-in-morse-code.tsx"),
  route("1-in-morse-code", "routes/1-in-morse-code.tsx"),
  route("2-in-morse-code", "routes/2-in-morse-code.tsx"),
  route("3-in-morse-code", "routes/3-in-morse-code.tsx"),
  route("4-in-morse-code", "routes/4-in-morse-code.tsx"),
  route("5-in-morse-code", "routes/5-in-morse-code.tsx"),
  route("6-in-morse-code", "routes/6-in-morse-code.tsx"),
  route("7-in-morse-code", "routes/7-in-morse-code.tsx"),
  route("8-in-morse-code", "routes/8-in-morse-code.tsx"),
  route("9-in-morse-code", "routes/9-in-morse-code.tsx"),
  route("morse-code-printable-chart", "routes/morse-code-printable-chart.tsx"),
  route(
    "morse-code-international-translator",
    "routes/morse-code-international-translator.tsx",
  ),
  route("morse-code-sos", "routes/morse-code-sos.tsx"),
  route("morse-code-sentence-practice", "routes/morse-code-sentence-practice.tsx"),
  route("learn-morse-code", "routes/learn-morse-code.tsx"),
  route("morse-code-history", "routes/morse-code-history.tsx"),
  route(
    "international-vs-american-morse-code",
    "routes/international-vs-american-morse-code.tsx",
  ),
  route("morse-code-emergency-signals", "routes/morse-code-emergency-signals.tsx"),
  route("morse-code-amateur-radio-cw", "routes/morse-code-amateur-radio-cw.tsx"),
  route("morse-code-timing", "routes/morse-code-timing.tsx"),
  route("farnsworth-timing", "routes/farnsworth-timing.tsx"),
  route("morse-code-word-trainer", "routes/morse-code-word-trainer.tsx"),
  route("sources", "routes/sources.tsx"),
  route("morse-code-prosigns", "routes/morse-code-prosigns.tsx"),
  route("morse-code-q-codes", "routes/morse-code-q-codes.tsx"),
  route("morse-code-punctuation", "routes/morse-code-punctuation.tsx"),
  route("morse-code-practice-plan", "routes/morse-code-practice-plan.tsx"),
  route("morse-code-test", "routes/morse-code-test.tsx"),
  route(
    "international-morse-code-reference",
    "routes/international-morse-code-reference.tsx",
  ),
  route("morse-code-audio-practice", "routes/morse-code-audio-practice.tsx"),
  route(
    "morse-code-word-search-builder",
    "routes/morse-code-word-search-builder.tsx",
  ),
  route("morse-code-visual-practice", "routes/morse-code-visual-practice.tsx"),
  route("morse-code-audio-quiz", "routes/morse-code-audio-quiz.tsx"),
  route("morse-code-visual-quiz", "routes/morse-code-visual-quiz.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorAudioAlias), "routes/morse-code-translator-audio.tsx"),
  route(routeSlug(ROUTES.audioMorseCodeTranslatorAlias), "routes/audio-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioTranslateAlias), "routes/morse-code-audio-translate.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslateAudioAlias), "routes/morse-code-translate-audio.tsx"),
  route(routeSlug(ROUTES.morseTranslatorAudioAlias), "routes/morse-translator-audio.tsx"),
  route(routeSlug(ROUTES.morseAudioTranslatorAlias), "routes/morse-audio-translator.tsx"),
  route(routeSlug(ROUTES.codeMorseTranslatorAudioAlias), "routes/code-morse-translator-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorWithAudioAlias), "routes/morse-code-translator-with-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorWithSoundAlias), "routes/morse-code-translator-with-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorSoundAlias), "routes/morse-code-translator-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorListenAlias), "routes/morse-code-translator-listen.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioTranslaterAlias), "routes/morse-code-audio-translater.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioFileAlias), "routes/morse-code-audio-file.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioAlias), "routes/morse-code-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundAlias), "routes/morse-code-sound.tsx"),
  route(routeSlug(ROUTES.morseAudioAlias), "routes/morse-audio.tsx"),
  route(routeSlug(ROUTES.morseSoundAlias), "routes/morse-sound.tsx"),
  route(routeSlug(ROUTES.audioMorseCodeAlias), "routes/audio-morse-code.tsx"),
  route(routeSlug(ROUTES.audioMorseAlias), "routes/audio-morse.tsx"),
  route(routeSlug(ROUTES.morsecodeSoundAlias), "routes/morsecode-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeInSoundAlias), "routes/morse-code-in-sound.tsx"),
  route(routeSlug(ROUTES.soundMorseCodeAlias), "routes/sound-morse-code.tsx"),
  route(routeSlug(ROUTES.codeMorseAudioAlias), "routes/code-morse-audio.tsx"),
  route(routeSlug(ROUTES.codeMorseSoundAlias), "routes/code-morse-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundButtonAlias), "routes/morse-code-sound-button.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundDownloadAlias), "routes/morse-code-sound-download.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundMp3Alias), "routes/morse-code-sound-mp3.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundTranslateAlias), "routes/morse-code-sound-translate.tsx"),
  route(routeSlug(ROUTES.morseCodeTextToSoundTranslatorAlias), "routes/morse-code-text-to-sound-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeSpeakerAlias), "routes/morse-code-speaker.tsx"),
  route(routeSlug(ROUTES.morseCodeVoiceAlias), "routes/morse-code-voice.tsx"),
  route(routeSlug(ROUTES.morseCodeTextToSpeechAlias), "routes/morse-code-text-to-speech.tsx"),
  route(routeSlug(ROUTES.morseCodeTtsAlias), "routes/morse-code-tts.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioEncoderAlias), "routes/morse-code-audio-encoder.tsx"),
  route(routeSlug(ROUTES.morseCodeConverterAudioAlias), "routes/morse-code-converter-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeToAudioGeneratorAlias), "routes/morse-code-to-audio-generator.tsx"),
  route(routeSlug(ROUTES.onlineMorseCodeAudioGeneratorAlias), "routes/online-morse-code-audio-generator.tsx"),
  route(routeSlug(ROUTES.textToMorseCodeAudioGeneratorAlias), "routes/text-to-morse-code-audio-generator.tsx"),
  route(routeSlug(ROUTES.morseCodeBeeperAlias), "routes/morse-code-beeper.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundEffectGeneratorAlias), "routes/morse-code-sound-effect-generator.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundEffectsAlias), "routes/morse-code-sound-effects.tsx"),
  route(routeSlug(ROUTES.morseCodeBeatMakerAlias), "routes/morse-code-beat-maker.tsx"),
  route(routeSlug(ROUTES.morseCodeMusicGeneratorAlias), "routes/morse-code-music-generator.tsx"),
  route(routeSlug(ROUTES.morseCodeToMusicAlias), "routes/morse-code-to-music.tsx"),
  route(routeSlug(ROUTES.makeMorseCodeAudioAlias), "routes/make-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.createMorseCodeAudioAlias), "routes/create-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.generateMorseCodeAudioAlias), "routes/generate-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.morseToAudioAlias), "routes/morse-to-audio.tsx"),
  route(routeSlug(ROUTES.morseToSoundAlias), "routes/morse-to-sound.tsx"),
  route(routeSlug(ROUTES.textToAudioMorseCodeAlias), "routes/text-to-audio-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeIntoAudioAlias), "routes/morse-code-into-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeIntoSoundAlias), "routes/morse-code-into-sound.tsx"),
  route(routeSlug(ROUTES.codeToSoundAlias), "routes/code-to-sound.tsx"),
  route(routeSlug(ROUTES.makeMorseCodeSoundAlias), "routes/make-morse-code-sound.tsx"),
  route(routeSlug(ROUTES.howToMakeMorseCodeSoundAlias), "routes/how-to-make-morse-code-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeRecordingAlias), "routes/morse-code-recording.tsx"),
  route(routeSlug(ROUTES.audioToMorseShortAlias), "routes/audio-to-morse.tsx"),
  route(routeSlug(ROUTES.soundToMorseCodeAlias), "routes/sound-to-morse-code.tsx"),
  route(routeSlug(ROUTES.mp3ToMorseCodeAlias), "routes/mp3-to-morse-code.tsx"),
  route(routeSlug(ROUTES.wavToMorseCodeAlias), "routes/wav-to-morse-code.tsx"),
  route(routeSlug(ROUTES.wavToMorseAlias), "routes/wav-to-morse.tsx"),
  route(routeSlug(ROUTES.morseCodeMp3ToTextAlias), "routes/morse-code-mp3-to-text.tsx"),
  route(routeSlug(ROUTES.morseCodeDecoderMp3Alias), "routes/morse-code-decoder-mp3.tsx"),
  route(routeSlug(ROUTES.morseCodeDecoderAudioAlias), "routes/morse-code-decoder-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeDecoderAudioToTextAlias), "routes/morse-code-decoder-audio-to-text.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioConverterAlias), "routes/morse-code-audio-converter.tsx"),
  route(routeSlug(ROUTES.morseAudioDecoderAlias), "routes/morse-audio-decoder.tsx"),
  route(routeSlug(ROUTES.morseDecoderAudioAlias), "routes/morse-decoder-audio.tsx"),
  route(routeSlug(ROUTES.decoderMorseAudioAlias), "routes/decoder-morse-audio.tsx"),
  route(routeSlug(ROUTES.morseDecoderAudioToTextAlias), "routes/morse-decoder-audio-to-text.tsx"),
  route(routeSlug(ROUTES.audioMorseCodeDecoderAlias), "routes/audio-morse-code-decoder.tsx"),
  route(routeSlug(ROUTES.audioMorseDecoderAlias), "routes/audio-morse-decoder.tsx"),
  route(routeSlug(ROUTES.audioMorseToTextAlias), "routes/audio-morse-to-text.tsx"),
  route(routeSlug(ROUTES.audioMorseCodeToTextAlias), "routes/audio-morse-code-to-text.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorFromAudioAlias), "routes/morse-code-translator-from-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorFromSoundAlias), "routes/morse-code-translator-from-sound.tsx"),
  route(routeSlug(ROUTES.translateMorseCodeFromAudioAlias), "routes/translate-morse-code-from-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundDecoderAlias), "routes/morse-code-sound-decoder.tsx"),
  route(routeSlug(ROUTES.morseCodeNoiseTranslatorAlias), "routes/morse-code-noise-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorSoundToTextAlias), "routes/morse-code-translator-sound-to-text.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioToTextTranslatorAlias), "routes/morse-code-audio-to-text-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorAudioToTextAlias), "routes/morse-code-translator-audio-to-text.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorAudioToNumbersAlias), "routes/morse-code-translator-audio-to-numbers.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorAudioNumbersAlias), "routes/morse-code-translator-audio-numbers.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioNumbersAlias), "routes/morse-code-audio-numbers.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorBySoundAlias), "routes/morse-code-translator-by-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeVoiceTranslatorAlias), "routes/morse-code-voice-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorVoiceAlias), "routes/morse-code-translator-voice.tsx"),
  route(routeSlug(ROUTES.audioMorseCodeToTextTranslatorAlias), "routes/audio-morse-code-to-text-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeGeneratorAlias), "routes/morse-code-generator.tsx"),
  route(routeSlug(ROUTES.morseGeneratorAlias), "routes/morse-generator.tsx"),
  route(routeSlug(ROUTES.generateMorseCodeAlias), "routes/generate-morse-code.tsx"),
  route(routeSlug(ROUTES.makeMorseCodeAlias), "routes/make-morse-code.tsx"),
  route(routeSlug(ROUTES.morsecodeMakerAlias), "routes/morsecode-maker.tsx"),
  route(routeSlug(ROUTES.morseCodeConverterAlias), "routes/morse-code-converter.tsx"),
  route(routeSlug(ROUTES.morseCodeToolAlias), "routes/morse-code-tool.tsx"),
  route(routeSlug(ROUTES.morseCodeTextAlias), "routes/morse-code-text.tsx"),
  route(routeSlug(ROUTES.textMorseCodeAlias), "routes/text-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeInTextAlias), "routes/morse-code-in-text.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorTextToMorseAlias), "routes/morse-code-translator-text-to-morse.tsx"),
  route(routeSlug(ROUTES.morseCodeAlphabetTranslatorAlias), "routes/morse-code-alphabet-translator.tsx"),
  route(routeSlug(ROUTES.letterMorseCodeTranslatorAlias), "routes/letter-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.codeWordsTranslatorAlias), "routes/code-words-translator.tsx"),
  route(routeSlug(ROUTES.wordCodeTranslatorAlias), "routes/word-code-translator.tsx"),
  route(routeSlug(ROUTES.wordsIntoMorseCodeTranslatorAlias), "routes/words-into-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.translateWordToMorseCodeAlias), "routes/translate-word-to-morse-code.tsx"),
  route(routeSlug(ROUTES.translateWordsIntoMorseCodeAlias), "routes/translate-words-into-morse-code.tsx"),
  route(routeSlug(ROUTES.convertToMorseCodeAlias), "routes/convert-to-morse-code.tsx"),
  route(routeSlug(ROUTES.toMorseAlias), "routes/to-morse.tsx"),
  route(routeSlug(ROUTES.translateMorseCodeAlias), "routes/translate-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslateAlias), "routes/morse-code-translate.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorTextAlias), "routes/morse-code-translator-text.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorsAlias), "routes/morse-code-translators.tsx"),
  route(routeSlug(ROUTES.morseCodeLiveTranslatorAlias), "routes/morse-code-live-translator.tsx"),
  route(routeSlug(ROUTES.liveMorseCodeTranslatorAlias), "routes/live-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeLanguageTranslatorAlias), "routes/morse-code-language-translator.tsx"),
  route(routeSlug(ROUTES.morseLanguageTranslatorAlias), "routes/morse-language-translator.tsx"),
  route(routeSlug(ROUTES.codeMorseTranslatorAlias), "routes/code-morse-translator.tsx"),
  route(routeSlug(ROUTES.decoderMorseCodeTranslatorAlias), "routes/decoder-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.inMorseCodeTranslatorAlias), "routes/in-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorChartAlias), "routes/morse-code-translator-chart.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorChartLettersAZAlias), "routes/morse-code-translator-chart-letters-a-z.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslatorToEnglishAlias), "routes/morse-code-translator-to-english.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslateToEnglishAlias), "routes/morse-code-translate-to-english.tsx"),
  route(routeSlug(ROUTES.morseToTextTranslatorAlias), "routes/morse-to-text-translator.tsx"),
  route(routeSlug(ROUTES.morseToEnglishTranslatorAlias), "routes/morse-to-english-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeToLettersAlias), "routes/morse-code-to-letters.tsx"),
  route(routeSlug(ROUTES.translateMorseCodeToWordsAlias), "routes/translate-morse-code-to-words.tsx"),
  route(routeSlug(ROUTES.morseCodeTranslateToWordsAlias), "routes/morse-code-translate-to-words.tsx"),
  route(routeSlug(ROUTES.morseCodeDecodeAlias), "routes/morse-code-decode.tsx"),
  route(routeSlug(ROUTES.decodeThisMorseCodeAlias), "routes/decode-this-morse-code.tsx"),
  route(routeSlug(ROUTES.decryptMorseCodeAlias), "routes/decrypt-morse-code.tsx"),
  route(routeSlug(ROUTES.unmorseCodeAlias), "routes/unmorse-code.tsx"),
  route(routeSlug(ROUTES.sosMorseCodeAlias), "routes/sos-morse-code.tsx"),
  route(routeSlug(ROUTES.sosInMorseCodeAlias), "routes/sos-in-morse-code.tsx"),
  route(routeSlug(ROUTES.sosMorseAlias), "routes/sos-morse.tsx"),
  route(routeSlug(ROUTES.sosCodeAlias), "routes/sos-code.tsx"),
  route(routeSlug(ROUTES.sosTranslatorAlias), "routes/sos-translator.tsx"),
  route(routeSlug(ROUTES.sosInMorseAlias), "routes/sos-in-morse.tsx"),
  route(routeSlug(ROUTES.sosMorseCodeTranslatorAlias), "routes/sos-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeSosTranslatorAlias), "routes/morse-code-sos-translator.tsx"),
  route(routeSlug(ROUTES.printableMorseCodeChartAlias), "routes/printable-morse-code-chart.tsx"),
  route(routeSlug(ROUTES.morseCodeChartPrintableAlias), "routes/morse-code-chart-printable.tsx"),
  route(routeSlug(ROUTES.morseCodePrintablePdfAlias), "routes/morse-code-printable-pdf.tsx"),
  route(routeSlug(ROUTES.morseCodePrintableChartPdfAlias), "routes/morse-code-printable-chart-pdf.tsx"),
  route(routeSlug(ROUTES.morseCodeChartPdfAlias), "routes/morse-code-chart-pdf.tsx"),
  route(routeSlug(ROUTES.morseCodeAlphabetChartPrintableAlias), "routes/morse-code-alphabet-chart-printable.tsx"),
  route(routeSlug(ROUTES.morseCodeAlphabetAToZPrintableAlias), "routes/morse-code-alphabet-a-to-z-printable.tsx"),
  route(routeSlug(ROUTES.morseCodePrintableAlias), "routes/morse-code-printable.tsx"),
  route(routeSlug(ROUTES.morseCodePrintableSheetAlias), "routes/morse-code-printable-sheet.tsx"),
  route(routeSlug(ROUTES.morseCodePrintableSheetsAlias), "routes/morse-code-printable-sheets.tsx"),
  route(routeSlug(ROUTES.morseCodeSheetAlias), "routes/morse-code-sheet.tsx"),
  route(routeSlug(ROUTES.morseCodePracticeSheetAlias), "routes/morse-code-practice-sheet.tsx"),
  route(routeSlug(ROUTES.morseCodePracticeSheetsAlias), "routes/morse-code-practice-sheets.tsx"),
  route(routeSlug(ROUTES.morseCodeNumberSheetAlias), "routes/morse-code-number-sheet.tsx"),
  route(routeSlug(ROUTES.morseCodeSheetNumbersAlias), "routes/morse-code-sheet-numbers.tsx"),
  route(routeSlug(ROUTES.morseCodeWorksheetAlias), "routes/morse-code-worksheet.tsx"),
  route(routeSlug(ROUTES.printableMorseCodeClueSheetGeneratorAlias), "routes/printable-morse-code-clue-sheet-generator.tsx"),
  route(routeSlug(ROUTES.howToLearnMorseCodeAlias), "routes/how-to-learn-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeLearningAlias), "routes/morse-code-learning.tsx"),
  route(routeSlug(ROUTES.learningMorseCodeAlias), "routes/learning-morse-code.tsx"),
  route(routeSlug(ROUTES.learningMorseCodeForBeginnersAlias), "routes/learning-morse-code-for-beginners.tsx"),
  route(routeSlug(ROUTES.morseAlphabetLearningAlias), "routes/morse-alphabet-learning.tsx"),
  route(routeSlug(ROUTES.morseCodeGuideAlias), "routes/morse-code-guide.tsx"),
  route(routeSlug(ROUTES.morseCodeForBeginnersAlias), "routes/morse-code-for-beginners.tsx"),
  route(routeSlug(ROUTES.learnMorseAlias), "routes/learn-morse.tsx"),
  route(routeSlug(ROUTES.morseCodeBeginnerAlias), "routes/morse-code-beginner.tsx"),
  route(routeSlug(ROUTES.morseCodeBeginnersAlias), "routes/morse-code-beginners.tsx"),
  route(routeSlug(ROUTES.morseCodeBasicAlias), "routes/morse-code-basic.tsx"),
  route(routeSlug(ROUTES.basicMorseCodeAlias), "routes/basic-morse-code.tsx"),
  route(routeSlug(ROUTES.buildAPersonalizedMorseCodePracticePlanForABeginnerAlias), "routes/build-a-personalized-morse-code-practice-plan-for-a-beginner.tsx"),
  route(routeSlug(ROUTES.howToDecodeMorseCodeAlias), "routes/how-to-decode-morse-code.tsx"),
  route(routeSlug(ROUTES.howToReadMorseAlias), "routes/how-to-read-morse.tsx"),
  route(routeSlug(ROUTES.readMorseShortAlias), "routes/read-morse.tsx"),
  route(routeSlug(ROUTES.readMorseCodeOnlineAlias), "routes/read-morse-code-online.tsx"),
  route(routeSlug(ROUTES.howToWriteMorseCodeAlias), "routes/how-to-write-morse-code.tsx"),
  route(routeSlug(ROUTES.writingMorseCodeAlias), "routes/writing-morse-code.tsx"),
  route(routeSlug(ROUTES.howDoYouWriteInMorseCodeAlias), "routes/how-do-you-write-in-morse-code.tsx"),
  route(routeSlug(ROUTES.howToWriteInMorseCodeOnPaperAlias), "routes/how-to-write-in-morse-code-on-paper.tsx"),
  route(routeSlug(ROUTES.morseCodeHowToWriteAlias), "routes/morse-code-how-to-write.tsx"),
  route(routeSlug(ROUTES.morseCodeWriteAlias), "routes/morse-code-write.tsx"),
  route(routeSlug(ROUTES.howToTypeMorseCodeAlias), "routes/how-to-type-morse-code.tsx"),
  route(routeSlug(ROUTES.typeMorseCodeAlias), "routes/type-morse-code.tsx"),
  route(routeSlug(ROUTES.typingMorseCodeAlias), "routes/typing-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeHowToTypeAlias), "routes/morse-code-how-to-type.tsx"),
  route(routeSlug(ROUTES.morseCodeTextingAlias), "routes/morse-code-texting.tsx"),
  route(routeSlug(ROUTES.howToTypeSpaceInMorseCodeAlias), "routes/how-to-type-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.howToTypeASpaceInMorseCodeAlias), "routes/how-to-type-a-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.howToAddSpaceInMorseCodeAlias), "routes/how-to-add-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.howDoYouDoASpaceInMorseCodeAlias), "routes/how-do-you-do-a-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.howToDoSpaceInMorseCodeAlias), "routes/how-to-do-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.howToPutASpaceInMorseCodeAlias), "routes/how-to-put-a-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeLanguageAlias), "routes/morse-code-language.tsx"),
  route(routeSlug(ROUTES.morseCodeLanguagesAlias), "routes/morse-code-languages.tsx"),
  route(routeSlug(ROUTES.morseCodeByLanguageTranslatorAlias), "routes/morse-code-by-language-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeWorldTranslatorAlias), "routes/morse-code-world-translator.tsx"),
  route(routeSlug(ROUTES.wabunCodeTranslatorAlias), "routes/wabun-code-translator.tsx"),
  route(routeSlug(ROUTES.wabunCodeAlias), "routes/wabun-code.tsx"),
  route(routeSlug(ROUTES.japaneseMorseCodeAlias), "routes/japanese-morse-code.tsx"),
  route(routeSlug(ROUTES.japaneseMorseCodeTranslatorAlias), "routes/japanese-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeTAlias), "routes/morse-code-t.tsx"),
  route(routeSlug(ROUTES.morseCodeCAlias), "routes/morse-code-c.tsx"),
  route(routeSlug(ROUTES.cMorseCodeAlias), "routes/c-morse-code.tsx"),
  route(routeSlug(ROUTES.letterOInMorseCodeAlias), "routes/letter-o-in-morse-code.tsx"),
  route(routeSlug(ROUTES.zInMorseAlias), "routes/z-in-morse.tsx"),
  route(routeSlug(ROUTES.letterZInMorseCodeAlias), "routes/letter-z-in-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeForZAlias), "routes/morse-code-for-z.tsx"),
  route(routeSlug(ROUTES.wMorseCodeAlias), "routes/w-morse-code.tsx"),
  route(routeSlug(ROUTES.qMorseCodeAlias), "routes/q-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeQAlias), "routes/morse-code-q.tsx"),
  route(routeSlug(ROUTES.pMorseCodeAlias), "routes/p-morse-code.tsx"),
  route(routeSlug(ROUTES.letterAInMorseCodeAlias), "routes/letter-a-in-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeForLetterAAlias), "routes/morse-code-for-letter-a.tsx"),
  route(routeSlug(ROUTES.uMorseCodeAlias), "routes/u-morse-code.tsx"),
  route(routeSlug(ROUTES.fMorseCodeAlias), "routes/f-morse-code.tsx"),
  route(routeSlug(ROUTES.gInMorseAlias), "routes/g-in-morse.tsx"),
  route(routeSlug(ROUTES.morseCodeOfVAlias), "routes/morse-code-of-v.tsx"),
  route(routeSlug(ROUTES.helpMorseCodeAlias), "routes/help-morse-code.tsx"),
  route(routeSlug(ROUTES.helpMeMorseCodeAlias), "routes/help-me-morse-code.tsx"),
  route(routeSlug(ROUTES.hiMorseCodeAlias), "routes/hi-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeForOkAlias), "routes/morse-code-for-ok.tsx"),
  route(routeSlug(ROUTES.morseCodeHelloAlias), "routes/morse-code-hello.tsx"),
  route(routeSlug(ROUTES.helloMorseCodeAlias), "routes/hello-morse-code.tsx"),
  route(routeSlug(ROUTES.iLoveUInMorseCodeAlias), "routes/i-love-u-in-morse-code.tsx"),
  route(routeSlug(ROUTES.doesMorseCodeHaveSpacesAlias), "routes/does-morse-code-have-spaces.tsx"),
  route(routeSlug(ROUTES.howToMakeASpaceInMorseCodeAlias), "routes/how-to-make-a-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeNoSpacesAlias), "routes/morse-code-no-spaces.tsx"),
  route(routeSlug(ROUTES.morseCodeWithNoSpacesAlias), "routes/morse-code-with-no-spaces.tsx"),
  route(routeSlug(ROUTES.morseWithoutSpacesAlias), "routes/morse-without-spaces.tsx"),
  route(routeSlug(ROUTES.slashMorseCodeAlias), "routes/slash-morse-code.tsx"),
  route(routeSlug(ROUTES.whatAreTheSlashesInMorseCodeAlias), "routes/what-are-the-slashes-in-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeHowToSeparateLettersAlias), "routes/morse-code-how-to-separate-letters.tsx"),
  route(routeSlug(ROUTES.morseCodeTesterAlias), "routes/morse-code-tester.tsx"),
  route(routeSlug(ROUTES.morseCodeVisualTestAlias), "routes/morse-code-visual-test.tsx"),
  route(routeSlug(ROUTES.morseCodeTestVisualVersionAlias), "routes/morse-code-test-visual-version.tsx"),
  route(routeSlug(ROUTES.morseCodeVisualQuizTestAlias), "routes/morse-code-visual-quiz-test.tsx"),
  route(routeSlug(ROUTES.morseCodeQuizSoundAlias), "routes/morse-code-quiz-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioTestAlias), "routes/morse-code-audio-test.tsx"),
  route(routeSlug(ROUTES.visualQuizTypoAlias), "routes/morse-code-vidual-quiz.tsx"),
  route("morse-code-sound-generator", "routes/morse-code-sound-generator.tsx"),
  route(
    "morse-code-mp3-generator",
    "routes/morse-code-mp3-generator.tsx",
  ),
  route("morse-code-book-translator", "routes/morse-code-book-translator.tsx"),
  route("morse-code-printable-pages", "routes/morse-code-printable-pages.tsx"),
  route("morse-code-books", "routes/morse-code-books.tsx"),
  route("morse-code-books/:slug/print", "routes/morse-code-books.$slug.print.tsx"),
  route("morse-code-books/:slug", "routes/morse-code-books.$slug.tsx"),
  route("morse-code-audiobooks", "routes/morse-code-audiobooks.tsx"),
  route("morse-code-audiobooks/:slug", "routes/morse-code-audiobooks.$slug.tsx"),
  route("morse-code-by-language", "routes/morse-code-by-language.tsx"),
  route(
    "morse-code-by-language/japanese",
    "routes/morse-code-by-language/japanese.tsx",
  ),
  route(
    "morse-code-by-language/russian",
    "routes/morse-code-by-language/russian.tsx",
  ),
  route(
    "morse-code-by-language/greek",
    "routes/morse-code-by-language/greek.tsx",
  ),
  route(
    "morse-book-content/books/:slug",
    "routes/morse-book-content.books.$slug.tsx",
  ),
  route("morse-code-video-generator", "routes/morse-code-video-generator.tsx"),
  route("how-to-read-morse-code", "routes/how-to-read-morse-code.tsx"),
  route("how-to-write-in-morse-code", "routes/how-to-write-in-morse-code.tsx"),
  route("how-to-type-in-morse-code", "routes/how-to-type-in-morse-code.tsx"),
  route("copy-and-paste-morse-code", "routes/copy-and-paste-morse-code.tsx"),
  route("morse-code-without-spaces", "routes/morse-code-without-spaces.tsx"),
  route(
    "how-to-separate-words-in-morse-code",
    "routes/how-to-separate-words-in-morse-code.tsx",
  ),
  route("i-love-you-in-morse-code", "routes/i-love-you-in-morse-code.tsx"),
  route("cq-in-morse-code", "routes/cq-in-morse-code.tsx"),
  route("hello-in-morse-code", "routes/hello-in-morse-code.tsx"),
  route("hi-in-morse-code", "routes/hi-in-morse-code.tsx"),
  route("help-in-morse-code", "routes/help-in-morse-code.tsx"),
  route("help-me-in-morse-code", "routes/help-me-in-morse-code.tsx"),
  route("yes-in-morse-code", "routes/yes-in-morse-code.tsx"),
  route("no-in-morse-code", "routes/no-in-morse-code.tsx"),
  route("ok-in-morse-code", "routes/ok-in-morse-code.tsx"),
  route("sorry-in-morse-code", "routes/sorry-in-morse-code.tsx"),
  route("love-in-morse-code", "routes/love-in-morse-code.tsx"),
  route("hello-world-in-morse-code", "routes/hello-world-in-morse-code.tsx"),
  route("test-in-morse-code", "routes/test-in-morse-code.tsx"),
  route("question-mark-in-morse-code", "routes/question-mark-in-morse-code.tsx"),
  route("at-sign-in-morse-code", "routes/at-sign-in-morse-code.tsx"),
  route("space-in-morse-code", "routes/space-in-morse-code.tsx"),
  route("slash-in-morse-code", "routes/slash-in-morse-code.tsx"),
  route("period-in-morse-code", "routes/period-in-morse-code.tsx"),
  route("comma-in-morse-code", "routes/comma-in-morse-code.tsx"),
  route(
    "exclamation-mark-in-morse-code",
    "routes/exclamation-mark-in-morse-code.tsx",
  ),
  route("apostrophe-in-morse-code", "routes/apostrophe-in-morse-code.tsx"),
  route("hyphen-in-morse-code", "routes/hyphen-in-morse-code.tsx"),
  route("colon-in-morse-code", "routes/colon-in-morse-code.tsx"),
  route("semicolon-in-morse-code", "routes/semicolon-in-morse-code.tsx"),
  route("equals-sign-in-morse-code", "routes/equals-sign-in-morse-code.tsx"),
  route("plus-sign-in-morse-code", "routes/plus-sign-in-morse-code.tsx"),
  route(
    "quotation-mark-in-morse-code",
    "routes/quotation-mark-in-morse-code.tsx",
  ),
  route("parentheses-in-morse-code", "routes/parentheses-in-morse-code.tsx"),
  route("ampersand-in-morse-code", "routes/ampersand-in-morse-code.tsx"),
  route("underscore-in-morse-code", "routes/underscore-in-morse-code.tsx"),
  route("contact", "routes/contact.tsx"),
  route("sitemap", "routes/sitemap.tsx"),

  // Redirects for old URLs. Ignore these routes
  route(routeSlug(ROUTES.translatorAlias), "routes/morse-code-translator.tsx"),
  route(routeSlug(ROUTES.morseCodeAlias), "routes/morse-code.tsx"),
  route(routeSlug(ROUTES.morseAlias), "routes/morse.tsx"),
  route(routeSlug(ROUTES.morsewordsAlias), "routes/morsewords.tsx"),
  route(routeSlug(ROUTES.morseWordsAlias), "routes/morse-words.tsx"),
  route(routeSlug(ROUTES.dictionaryAlias), "routes/morse-code-dictionary.tsx"),
  route(routeSlug(ROUTES.wordGameAlias), "routes/morse-code-word-game.tsx"),
  route(routeSlug(ROUTES.audioTranslatorAlias), "routes/morse-code-audio-translator.tsx"),
  route(routeSlug(ROUTES.audioGeneratorAlias), "routes/morse-code-audio-generator.tsx"),
  route(routeSlug(ROUTES.generatorAudioAlias), "routes/morse-code-generator-audio.tsx"),
  route(routeSlug(ROUTES.audioMakerAlias), "routes/morse-code-audio-maker.tsx"),
  route(routeSlug(ROUTES.soundMakerAlias), "routes/morse-code-sound-maker.tsx"),
  route(routeSlug(ROUTES.generatorSoundAlias), "routes/morse-code-generator-sound.tsx"),
  route(routeSlug(ROUTES.morseSoundGeneratorAlias), "routes/morse-sound-generator.tsx"),
  route(routeSlug(ROUTES.morseAudioGeneratorAlias), "routes/morse-audio-generator.tsx"),
  route(routeSlug(ROUTES.morseCodeToAudioAlias), "routes/morse-code-to-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeToSoundAlias), "routes/morse-code-to-sound.tsx"),
  route(routeSlug(ROUTES.textToMorseCodeAudioAlias), "routes/text-to-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.textToMorseAudioAlias), "routes/text-to-morse-audio.tsx"),
  route(routeSlug(ROUTES.textToMorseCodeSoundAlias), "routes/text-to-morse-code-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeTextToAudioAlias), "routes/morse-code-text-to-audio.tsx"),
  route(routeSlug(ROUTES.morseCodeTextToSoundAlias), "routes/morse-code-text-to-sound.tsx"),
  route(routeSlug(ROUTES.beepGeneratorAlias), "routes/morse-code-beep-generator.tsx"),
  route(routeSlug(ROUTES.toneGeneratorAlias), "routes/morse-code-tone-generator.tsx"),
  route(routeSlug(ROUTES.noiseMakerAlias), "routes/morse-code-noise-maker.tsx"),
  route(
    routeSlug(ROUTES.soundGeneratorOnlineAlias),
    "routes/morse-code-sound-generator-online.tsx",
  ),
  route(routeSlug(ROUTES.textToMorseAlias), "routes/text-to-morse-code.tsx"),
  route(routeSlug(ROUTES.textToMorseShortAlias), "routes/text-to-morse.tsx"),
  route(routeSlug(ROUTES.englishToMorseCodeAlias), "routes/english-to-morse-code.tsx"),
  route(routeSlug(ROUTES.englishToMorseAlias), "routes/english-to-morse.tsx"),
  route(routeSlug(ROUTES.wordToMorseCodeAlias), "routes/word-to-morse-code.tsx"),
  route(routeSlug(ROUTES.wordsToMorseCodeAlias), "routes/words-to-morse-code.tsx"),
  route(routeSlug(ROUTES.lettersToMorseCodeAlias), "routes/letters-to-morse-code.tsx"),
  route(routeSlug(ROUTES.sentenceToMorseCodeAlias), "routes/sentence-to-morse-code.tsx"),
  route(routeSlug(ROUTES.normalTextToMorseCodeAlias), "routes/normal-text-to-morse-code.tsx"),
  route(routeSlug(ROUTES.convertTextToMorseCodeAlias), "routes/convert-text-to-morse-code.tsx"),
  route(routeSlug(ROUTES.translateToMorseCodeAlias), "routes/translate-to-morse-code.tsx"),
  route(
    routeSlug(ROUTES.translateWordsToMorseCodeAlias),
    "routes/translate-words-to-morse-code.tsx",
  ),
  route(routeSlug(ROUTES.textIntoMorseCodeAlias), "routes/text-into-morse-code.tsx"),
  route(routeSlug(ROUTES.wordIntoMorseCodeAlias), "routes/word-into-morse-code.tsx"),
  route(routeSlug(ROUTES.typeInMorseCodeAlias), "routes/type-in-morse-code.tsx"),
  route(routeSlug(ROUTES.writeInMorseCodeAlias), "routes/write-in-morse-code.tsx"),
  route(routeSlug(ROUTES.writeMorseCodeAlias), "routes/write-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeWriterAlias), "routes/morse-code-writer.tsx"),
  route(routeSlug(ROUTES.morseCodeCreatorAlias), "routes/morse-code-creator.tsx"),
  route(routeSlug(ROUTES.morseCodeMakerAlias), "routes/morse-code-maker.tsx"),
  route(routeSlug(ROUTES.morseToTextAlias), "routes/morse-to-text.tsx"),
  route(routeSlug(ROUTES.morseCodeToTextAlias), "routes/morse-code-to-text.tsx"),
  route(routeSlug(ROUTES.morseToWordsAlias), "routes/morse-to-words.tsx"),
  route(routeSlug(ROUTES.morseCodeToWordsAlias), "routes/morse-code-to-words.tsx"),
  route(routeSlug(ROUTES.decodeMorseCodeAlias), "routes/decode-morse-code.tsx"),
  route(routeSlug(ROUTES.decodingMorseCodeAlias), "routes/decoding-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeDecipherAlias), "routes/morse-code-decipher.tsx"),
  route(routeSlug(ROUTES.morseCodeSolverAlias), "routes/morse-code-solver.tsx"),
  route(routeSlug(ROUTES.morseCodeDecrypterAlias), "routes/morse-code-decrypter.tsx"),
  route(routeSlug(ROUTES.morseCodeUnscramblerAlias), "routes/morse-code-unscrambler.tsx"),
  route(routeSlug(ROUTES.morseCodeInterpreterAlias), "routes/morse-code-interpreter.tsx"),
  route(routeSlug(ROUTES.morseDecoderAlias), "routes/morse-decoder.tsx"),
  route(
    routeSlug(ROUTES.morseCodeTranslateToTextAlias),
    "routes/morse-code-translate-to-text.tsx",
  ),
  route(
    routeSlug(ROUTES.convertMorseCodeToTextAlias),
    "routes/convert-morse-code-to-text.tsx",
  ),
  route(routeSlug(ROUTES.decodeMorseAlias), "routes/decode-morse.tsx"),
  route(routeSlug(ROUTES.convertMorseToTextAlias), "routes/convert-morse-to-text.tsx"),
  route(
    routeSlug(ROUTES.morseCodeTranslatorToTextAlias),
    "routes/morse-code-translator-to-text.tsx",
  ),
  route(
    routeSlug(ROUTES.morseCodeTranslatorToWordsAlias),
    "routes/morse-code-translator-to-words.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeIntoWordsAlias), "routes/morse-code-into-words.tsx"),
  route(
    routeSlug(ROUTES.morseCodeToWordsTranslatorAlias),
    "routes/morse-code-to-words-translator.tsx",
  ),
  route(
    routeSlug(ROUTES.morseCodeTranslatorMorseToTextAlias),
    "routes/morse-code-translator-morse-to-text.tsx",
  ),
  route(routeSlug(ROUTES.morseToWordAlias), "routes/morse-to-word.tsx"),
  route(routeSlug(ROUTES.morseCodeToWordAlias), "routes/morse-code-to-word.tsx"),
  route(routeSlug(ROUTES.audioToMorseAlias), "routes/audio-to-morse-code.tsx"),
  route(routeSlug(ROUTES.audioToTextAlias), "routes/morse-code-audio-to-text.tsx"),
  route(routeSlug(ROUTES.audioToTextMorseCodeAlias), "routes/audio-to-text-morse-code.tsx"),
  route(routeSlug(ROUTES.morseAudioToTextAlias), "routes/morse-audio-to-text.tsx"),
  route(routeSlug(ROUTES.morseSoundToTextAlias), "routes/morse-sound-to-text.tsx"),
  route(routeSlug(ROUTES.soundToTextAlias), "routes/morse-code-sound-to-text.tsx"),
  route(routeSlug(ROUTES.fromAudioAlias), "routes/morse-code-from-audio.tsx"),
  route(routeSlug(ROUTES.fromSoundAlias), "routes/morse-code-from-sound.tsx"),
  route(routeSlug(ROUTES.soundTranslatorAlias), "routes/morse-code-sound-translator.tsx"),
  route(
    routeSlug(ROUTES.soundToMorseTranslatorAlias),
    "routes/sound-to-morse-code-translator.tsx",
  ),
  route(
    routeSlug(ROUTES.audioToMorseTranslatorAlias),
    "routes/audio-to-morse-code-translator.tsx",
  ),
  route(
    routeSlug(ROUTES.audioDecoderOnlineAlias),
    "routes/morse-code-audio-decoder-online.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeMp3DecoderAlias), "routes/morse-code-mp3-decoder.tsx"),
  route(routeSlug(ROUTES.translateAudioAlias), "routes/translate-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.realtimeAudioDecoderAlias), "routes/real-time-morse-code-decoder.tsx"),
  route(routeSlug(ROUTES.mp3AudioDecoderAlias), "routes/mp3-morse-code-decoder.tsx"),
  route(routeSlug(ROUTES.wavAudioDecoderAlias), "routes/wav-morse-code-decoder.tsx"),
  route(routeSlug(ROUTES.morseCodeWavDecoderAlias), "routes/morse-code-wav-decoder.tsx"),
  route(
    routeSlug(ROUTES.audioTranslatorToTextAlias),
    "routes/morse-code-audio-translator-to-text.tsx",
  ),
  route(
    routeSlug(ROUTES.translateAudioToTextAlias),
    "routes/translate-morse-code-audio-to-text.tsx",
  ),
  route(routeSlug(ROUTES.decodeFromAudioAlias), "routes/decode-morse-code-from-audio.tsx"),
  route(routeSlug(ROUTES.howToDecodeAudioAlias), "routes/how-to-decode-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.alphabetAToZAlias), "routes/morse-code-alphabet-a-to-z.tsx"),
  route(routeSlug(ROUTES.morseCodeAToZAlias), "routes/morse-code-a-to-z.tsx"),
  route(routeSlug(ROUTES.morseCodeAZAlias), "routes/morse-code-a-z.tsx"),
  route(routeSlug(ROUTES.morseAlphabetAlias), "routes/morse-alphabet.tsx"),
  route(routeSlug(ROUTES.morseCodeAbcAlias), "routes/morse-code-abc.tsx"),
  route(routeSlug(ROUTES.letterChartAlias), "routes/morse-code-letter-chart.tsx"),
  route(routeSlug(ROUTES.lettersChartAlias), "routes/morse-code-letters-chart.tsx"),
  route(
    routeSlug(ROUTES.alphabetCopyPasteAlias),
    "routes/morse-code-alphabet-copy-and-paste.tsx",
  ),
  route(
    routeSlug(ROUTES.alphabetAToZCopyPasteAlias),
    "routes/morse-code-alphabet-a-to-z-copy-and-paste.tsx",
  ),
  route(routeSlug(ROUTES.alphabetInMorseCodeAlias), "routes/alphabet-in-morse-code.tsx"),
  route(routeSlug(ROUTES.aToZInMorseCodeAlias), "routes/a-to-z-in-morse-code.tsx"),
  route(routeSlug(ROUTES.lettersInMorseCodeAlias), "routes/letters-in-morse-code.tsx"),
  route(routeSlug(ROUTES.internationalChartAlias), "routes/international-morse-code-chart.tsx"),
  route(routeSlug(ROUTES.chartAz09Alias), "routes/morse-code-chart-a-z-0-9.tsx"),
  route(routeSlug(ROUTES.alphabetChartAlias), "routes/morse-code-alphabet-chart.tsx"),
  route(routeSlug(ROUTES.chartAZAlias), "routes/morse-code-chart-a-z.tsx"),
  route(routeSlug(ROUTES.chartAToZAlias), "routes/morse-code-chart-a-to-z.tsx"),
  route(routeSlug(ROUTES.chartLettersAlias), "routes/morse-code-chart-letters.tsx"),
  route(
    routeSlug(ROUTES.chartLettersNumbersAlias),
    "routes/morse-code-chart-letters-numbers.tsx",
  ),
  route(
    routeSlug(ROUTES.chartLettersNumbersPunctuationAlias),
    "routes/morse-code-chart-letters-numbers-punctuation.tsx",
  ),
  route(routeSlug(ROUTES.symbolsAlias), "routes/morse-code-symbols.tsx"),
  route(routeSlug(ROUTES.symbolChartAlias), "routes/morse-code-symbol-chart.tsx"),
  route(routeSlug(ROUTES.referenceChartAlias), "routes/morse-code-reference-chart.tsx"),
  route(routeSlug(ROUTES.morseCodeTableAlias), "routes/morse-code-table.tsx"),
  route(
    routeSlug(ROUTES.internationalAlphabetAlias),
    "routes/international-morse-code-alphabet.tsx",
  ),
  route(
    routeSlug(ROUTES.internationalReferenceChartAlias),
    "routes/international-morse-code-reference-chart.tsx",
  ),
  route(routeSlug(ROUTES.officialChartAlias), "routes/official-morse-code-chart.tsx"),
  route(routeSlug(ROUTES.morseCodeOfficialChartAlias), "routes/morse-code-official-chart.tsx"),
  route(routeSlug(ROUTES.morseCodeSourceAlias), "routes/morse-code-source.tsx"),
  route(
    routeSlug(ROUTES.morseCodeOfficialReferenceAlias),
    "routes/morse-code-official-reference.tsx",
  ),
  route(routeSlug(ROUTES.ituMorseCodeAlias), "routes/itu-morse-code.tsx"),
  route(routeSlug(ROUTES.ituMorseCodeChartAlias), "routes/itu-morse-code-chart.tsx"),
  route(routeSlug(ROUTES.ituRM1677MorseCodeAlias), "routes/itu-r-m1677-morse-code.tsx"),
  route(routeSlug(ROUTES.ituRM16771Alias), "routes/itu-r-m-1677-1.tsx"),
  route(
    routeSlug(ROUTES.standardInternationalAlphabetAlias),
    "routes/standard-international-morse-code-alphabet.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeSlashAlias), "routes/morse-code-slash.tsx"),
  route(routeSlug(ROUTES.slashMeaningAlias), "routes/what-does-slash-mean-in-morse-code.tsx"),
  route(routeSlug(ROUTES.aSlashMeaningAlias), "routes/what-does-a-slash-mean-in-morse-code.tsx"),
  route(routeSlug(ROUTES.slashInMorseAlias), "routes/slash-in-morse.tsx"),
  route(
    routeSlug(ROUTES.slashSeparateWordsAlias),
    "routes/slash-used-to-separate-words-in-morse-code.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeSpaceAlias), "routes/morse-code-space.tsx"),
  route(routeSlug(ROUTES.morseCodeSpacesAlias), "routes/morse-code-spaces.tsx"),
  route(routeSlug(ROUTES.spacesInMorseCodeAlias), "routes/spaces-in-morse-code.tsx"),
  route(routeSlug(ROUTES.whatIsSpaceInMorseCodeAlias), "routes/what-is-space-in-morse-code.tsx"),
  route(routeSlug(ROUTES.howToWriteSpaceAlias), "routes/how-to-write-space-in-morse-code.tsx"),
  route(
    routeSlug(ROUTES.howToWriteASpaceAlias),
    "routes/how-to-write-a-space-in-morse-code.tsx",
  ),
  route(routeSlug(ROUTES.howToPutSpacesAlias), "routes/how-to-put-spaces-in-morse-code.tsx"),
  route(
    routeSlug(ROUTES.slashWordSeparatorAlias),
    "routes/morse-code-slash-word-separator.tsx",
  ),
  route(
    routeSlug(ROUTES.wordSeparatorSlashAlias),
    "routes/morse-code-word-separator-slash.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeSpacingAlias), "routes/morse-code-spacing.tsx"),
  route(
    routeSlug(ROUTES.spaceBetweenWordsAlias),
    "routes/morse-code-space-between-words.tsx",
  ),
  route(routeSlug(ROUTES.slashSeparatorAlias), "routes/morse-code-slash-separator.tsx"),
  route(
    routeSlug(ROUTES.slashSeparatorWordsAlias),
    "routes/morse-code-slash-separator-words.tsx",
  ),
  route(
    routeSlug(ROUTES.slashSeparatorWordAlias),
    "routes/morse-code-slash-separator-word.tsx",
  ),
  route(
    routeSlug(ROUTES.slashBetweenWordsAlias),
    "routes/morse-code-slash-between-words.tsx",
  ),
  route(routeSlug(ROUTES.wordBreakAlias), "routes/morse-code-word-break.tsx"),
  route(
    routeSlug(ROUTES.howWordsSeparatedAlias),
    "routes/how-are-words-separated-in-morse-code.tsx",
  ),
  route(
    routeSlug(ROUTES.separateLettersAlias),
    "routes/how-to-separate-letters-in-morse-code.tsx",
  ),
  route(
    routeSlug(ROUTES.separateMorseLettersAlias),
    "routes/how-to-separate-morse-code-letters.tsx",
  ),
  route(
    routeSlug(ROUTES.differentiateLettersAlias),
    "routes/how-to-differentiate-letters-in-morse-code.tsx",
  ),
  route(routeSlug(ROUTES.numbersInMorseCodeAlias), "routes/numbers-in-morse-code.tsx"),
  route(routeSlug(ROUTES.numberInMorseCodeAlias), "routes/number-in-morse-code.tsx"),
  route(routeSlug(ROUTES.numberMorseCodeAlias), "routes/number-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeNumberAlias), "routes/morse-code-number.tsx"),
  route(routeSlug(ROUTES.morseNumbersAlias), "routes/morse-numbers.tsx"),
  route(routeSlug(ROUTES.morseCodeDigitsAlias), "routes/morse-code-digits.tsx"),
  route(routeSlug(ROUTES.numbers09Alias), "routes/morse-code-numbers-0-9.tsx"),
  route(routeSlug(ROUTES.numbers110Alias), "routes/morse-code-numbers-1-10.tsx"),
  route(routeSlug(ROUTES.numberChartAlias), "routes/morse-code-number-chart.tsx"),
  route(routeSlug(ROUTES.digitChartAlias), "routes/morse-code-digit-chart.tsx"),
  route(routeSlug(ROUTES.numbersChartAlias), "routes/morse-code-numbers-chart.tsx"),
  route(
    routeSlug(ROUTES.doesMorseHaveNumbersAlias),
    "routes/does-morse-code-have-numbers.tsx",
  ),
  route(routeSlug(ROUTES.zeroInMorseCodeAlias), "routes/zero-in-morse-code.tsx"),
  route(routeSlug(ROUTES.oneInMorseCodeAlias), "routes/one-in-morse-code.tsx"),
  route(routeSlug(ROUTES.twoInMorseCodeAlias), "routes/two-in-morse-code.tsx"),
  route(routeSlug(ROUTES.threeInMorseCodeAlias), "routes/three-in-morse-code.tsx"),
  route(routeSlug(ROUTES.fourInMorseCodeAlias), "routes/four-in-morse-code.tsx"),
  route(routeSlug(ROUTES.fiveInMorseCodeAlias), "routes/five-in-morse-code.tsx"),
  route(routeSlug(ROUTES.sixInMorseCodeAlias), "routes/six-in-morse-code.tsx"),
  route(routeSlug(ROUTES.sevenInMorseCodeAlias), "routes/seven-in-morse-code.tsx"),
  route(routeSlug(ROUTES.eightInMorseCodeAlias), "routes/eight-in-morse-code.tsx"),
  route(routeSlug(ROUTES.nineInMorseCodeAlias), "routes/nine-in-morse-code.tsx"),
  route(
    routeSlug(ROUTES.punctuationInMorseCodeAlias),
    "routes/punctuation-in-morse-code.tsx",
  ),
  route(routeSlug(ROUTES.morsePunctuationAlias), "routes/morse-punctuation.tsx"),
  route(routeSlug(ROUTES.punctuationChartAlias), "routes/morse-code-punctuation-chart.tsx"),
  route(
    routeSlug(ROUTES.punctuationMarksAlias),
    "routes/morse-code-punctuation-marks.tsx",
  ),
  route(
    routeSlug(ROUTES.punctuationSymbolsAlias),
    "routes/morse-code-punctuation-symbols.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeQuestionMarkAlias), "routes/morse-code-question-mark.tsx"),
  route(routeSlug(ROUTES.questionMarkMorseCodeAlias), "routes/question-mark-morse-code.tsx"),
  route(
    routeSlug(ROUTES.morseCodeForQuestionMarkAlias),
    "routes/morse-code-for-question-mark.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeCommaAlias), "routes/morse-code-comma.tsx"),
  route(routeSlug(ROUTES.commaMorseCodeAlias), "routes/comma-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodePeriodAlias), "routes/morse-code-period.tsx"),
  route(routeSlug(ROUTES.periodMorseCodeAlias), "routes/period-morse-code.tsx"),
  route(routeSlug(ROUTES.fullStopAlias), "routes/full-stop-in-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeApostropheAlias), "routes/morse-code-apostrophe.tsx"),
  route(routeSlug(ROUTES.apostropheMorseCodeAlias), "routes/apostrophe-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeSemicolonAlias), "routes/morse-code-semicolon.tsx"),
  route(routeSlug(ROUTES.semicolonMorseCodeAlias), "routes/semicolon-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeColonAlias), "routes/morse-code-colon.tsx"),
  route(routeSlug(ROUTES.colonMorseCodeAlias), "routes/colon-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeHyphenAlias), "routes/morse-code-hyphen.tsx"),
  route(routeSlug(ROUTES.hyphenMorseCodeAlias), "routes/hyphen-morse-code.tsx"),
  route(
    routeSlug(ROUTES.morseCodeExclamationMarkAlias),
    "routes/morse-code-exclamation-mark.tsx",
  ),
  route(
    routeSlug(ROUTES.morseCodeExclamationPointAlias),
    "routes/morse-code-exclamation-point.tsx",
  ),
  route(
    routeSlug(ROUTES.exclamationPointAlias),
    "routes/exclamation-point-in-morse-code.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeAtSignAlias), "routes/morse-code-at-sign.tsx"),
  route(routeSlug(ROUTES.atSignMorseCodeAlias), "routes/at-sign-morse-code.tsx"),
  route(
    routeSlug(ROUTES.slashPunctuationAlias),
    "routes/morse-code-slash-punctuation.tsx",
  ),
  route(
    routeSlug(ROUTES.morseCodeQuotationMarkAlias),
    "routes/morse-code-quotation-mark.tsx",
  ),
  route(
    routeSlug(ROUTES.quotationMarkMorseCodeAlias),
    "routes/quotation-mark-morse-code.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeParenthesesAlias), "routes/morse-code-parentheses.tsx"),
  route(routeSlug(ROUTES.morseCodeAmpersandAlias), "routes/morse-code-ampersand.tsx"),
  route(routeSlug(ROUTES.morseCodeUnderscoreAlias), "routes/morse-code-underscore.tsx"),
  route(routeSlug(ROUTES.morseCodeEqualsSignAlias), "routes/morse-code-equals-sign.tsx"),
  route(routeSlug(ROUTES.morseCodePlusSignAlias), "routes/morse-code-plus-sign.tsx"),
  route(routeSlug(ROUTES.morseCodePracticeAlias), "routes/morse-code-practice.tsx"),
  route(routeSlug(ROUTES.practiceMorseCodeAlias), "routes/practice-morse-code.tsx"),
  route(routeSlug(ROUTES.morsePracticeAlias), "routes/morse-practice.tsx"),
  route(routeSlug(ROUTES.practiceMorseAlias), "routes/practice-morse.tsx"),
  route(routeSlug(ROUTES.morseCodeExercisesAlias), "routes/morse-code-exercises.tsx"),
  route(routeSlug(ROUTES.morseCodeExerciseAlias), "routes/morse-code-exercise.tsx"),
  route(routeSlug(ROUTES.morseCodeTrainingAlias), "routes/morse-code-training.tsx"),
  route(routeSlug(ROUTES.morseCodeTrainerAlias), "routes/morse-code-trainer.tsx"),
  route(routeSlug(ROUTES.morseCodeQuizAlias), "routes/morse-code-quiz.tsx"),
  route(routeSlug(ROUTES.morseQuizAlias), "routes/morse-quiz.tsx"),
  route(routeSlug(ROUTES.morseCodeQuizzesAlias), "routes/morse-code-quizzes.tsx"),
  route(routeSlug(ROUTES.morseCodeOnlineTestAlias), "routes/morse-code-online-test.tsx"),
  route(routeSlug(ROUTES.practiceWordsAlias), "routes/morse-code-practice-words.tsx"),
  route(routeSlug(ROUTES.wordPracticeAlias), "routes/morse-code-word-practice.tsx"),
  route(routeSlug(ROUTES.wordsPracticeAlias), "routes/morse-code-words-practice.tsx"),
  route(
    routeSlug(ROUTES.wordListTrainerAlias),
    "routes/morse-code-word-list-trainer.tsx",
  ),
  route(routeSlug(ROUTES.wordListTrainerShortAlias), "routes/word-list-trainer.tsx"),
  route(routeSlug(ROUTES.morseWordTrainerAlias), "routes/morse-word-trainer.tsx"),
  route(routeSlug(ROUTES.morseWordsTrainerAlias), "routes/morse-words-trainer.tsx"),
  route(
    routeSlug(ROUTES.practiceSentencesAlias),
    "routes/morse-code-practice-sentences.tsx",
  ),
  route(
    routeSlug(ROUTES.sentencesPracticeAlias),
    "routes/morse-code-sentences-practice.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeSentenceAlias), "routes/morse-code-sentence.tsx"),
  route(routeSlug(ROUTES.morseCodeSentencesAlias), "routes/morse-code-sentences.tsx"),
  route(routeSlug(ROUTES.morseSentencesAlias), "routes/morse-sentences.tsx"),
  route(routeSlug(ROUTES.exampleSentenceAlias), "routes/morse-code-example-sentence.tsx"),
  route(
    routeSlug(ROUTES.exampleOfSentenceAlias),
    "routes/example-of-morse-code-sentence.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeExamplesAlias), "routes/morse-code-examples.tsx"),
  route(routeSlug(ROUTES.messageMakerAlias), "routes/morse-code-message-maker.tsx"),
  route(routeSlug(ROUTES.createMessageAlias), "routes/create-morse-code-message.tsx"),
  route(routeSlug(ROUTES.morseCodeTypingAlias), "routes/morse-code-typing.tsx"),
  route(routeSlug(ROUTES.morseCodeTyperAlias), "routes/morse-code-typer.tsx"),
  route(routeSlug(ROUTES.morseTyperAlias), "routes/morse-typer.tsx"),
  route(routeSlug(ROUTES.morseTypingAlias), "routes/morse-typing.tsx"),
  route(routeSlug(ROUTES.morseCodeTypewriterAlias), "routes/morse-code-typewriter.tsx"),
  route(routeSlug(ROUTES.typingPracticeAlias), "routes/morse-code-typing-practice.tsx"),
  route(routeSlug(ROUTES.practiceTypingAlias), "routes/morse-code-practice-typing.tsx"),
  route(routeSlug(ROUTES.morseTypingTrainerAlias), "routes/morse-typing-trainer.tsx"),
  route(routeSlug(ROUTES.morseTypingPracticeAlias), "routes/morse-typing-practice.tsx"),
  route(routeSlug(ROUTES.morseCodeInputAlias), "routes/morse-code-input.tsx"),
  route(routeSlug(ROUTES.inputTranslatorAlias), "routes/morse-code-input-translator.tsx"),
  route(routeSlug(ROUTES.morseDictionaryAlias), "routes/morse-dictionary.tsx"),
  route(routeSlug(ROUTES.morseVocabularyAlias), "routes/morse-code-vocabulary.tsx"),
  route(routeSlug(ROUTES.morseCodeWordAlias), "routes/morse-code-word.tsx"),
  route(routeSlug(ROUTES.morseWordAlias), "routes/morse-word.tsx"),
  route(routeSlug(ROUTES.wordLookupAlias), "routes/morse-code-word-lookup.tsx"),
  route(routeSlug(ROUTES.morseCodeFinderAlias), "routes/morse-code-finder.tsx"),
  route(routeSlug(ROUTES.morseCodeLookupAlias), "routes/morse-code-lookup.tsx"),
  route(
    routeSlug(ROUTES.morseCodeCopyAndPasteAlias),
    "routes/morse-code-copy-and-paste.tsx",
  ),
  route(routeSlug(ROUTES.morseCodeCopyPasteAlias), "routes/morse-code-copy-paste.tsx"),
  route(routeSlug(ROUTES.copyMorseCodeAlias), "routes/copy-morse-code.tsx"),
  route(routeSlug(ROUTES.copyAndPasteMorseAlias), "routes/copy-and-paste-morse.tsx"),
  route(
    routeSlug(ROUTES.alphabetCopyPasteShortAlias),
    "routes/morse-code-alphabet-copy-paste.tsx",
  ),
  route(routeSlug(ROUTES.copyPasteMorseCodeAlias), "routes/copy-paste-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeReadAlias), "routes/morse-code-read.tsx"),
  route(routeSlug(ROUTES.morseCodeReadingAlias), "routes/morse-code-reading.tsx"),
  route(routeSlug(ROUTES.readerOnlineAlias), "routes/morse-code-reader-online.tsx"),
  route(routeSlug(ROUTES.audioReaderAlias), "routes/morse-code-audio-reader.tsx"),
  route(routeSlug(ROUTES.listenerAlias), "routes/morse-code-listener.tsx"),
  route(routeSlug(ROUTES.listenAndReadAlias), "routes/morse-code-listen-and-read.tsx"),
  route(
    routeSlug(ROUTES.listeningPracticeAlias),
    "routes/morse-code-listening-practice.tsx",
  ),
  route(
    routeSlug(ROUTES.hearingPracticeAlias),
    "routes/morse-code-hearing-practice.tsx",
  ),
  route(routeSlug(ROUTES.hearingAlias), "routes/morse-code-hearing.tsx"),
  route(routeSlug(ROUTES.hearMorseCodeAlias), "routes/hear-morse-code.tsx"),
  route(routeSlug(ROUTES.listenToMorseCodeAlias), "routes/listen-to-morse-code.tsx"),
  route(routeSlug(ROUTES.morseCodeListenAlias), "routes/morse-code-listen.tsx"),
  route(routeSlug(ROUTES.bySoundAlias), "routes/morse-code-by-sound.tsx"),
  route(routeSlug(ROUTES.byEarAlias), "routes/morse-code-by-ear.tsx"),
  route(routeSlug(ROUTES.playMorseCodeAlias), "routes/play-morse-code.tsx"),
  route(routeSlug(ROUTES.playMorseCodeSoundAlias), "routes/play-morse-code-sound.tsx"),
  route(routeSlug(ROUTES.audioPlayerAlias), "routes/morse-code-audio-player.tsx"),
  route(routeSlug(ROUTES.morseCodePlayerAlias), "routes/morse-code-player.tsx"),
  route(routeSlug(ROUTES.morseCodeWithSoundAlias), "routes/morse-code-with-sound.tsx"),
  route(routeSlug(ROUTES.morseCodeSoundsAlias), "routes/morse-code-sounds.tsx"),
  route(routeSlug(ROUTES.morseCodeBeepSoundAlias), "routes/morse-code-beep-sound.tsx"),
  route(routeSlug(ROUTES.practiceTestAlias), "routes/morse-code-practice-test.tsx"),
  route(routeSlug(ROUTES.listeningTestAlias), "routes/morse-code-listening-test.tsx"),
  route(routeSlug(ROUTES.typingTestAlias), "routes/morse-code-typing-test.tsx"),
  route(routeSlug(ROUTES.speedTestAlias), "routes/morse-code-speed-test.tsx"),
  route(routeSlug(ROUTES.morseTypeTestAlias), "routes/morse-type-test.tsx"),
  route(routeSlug(ROUTES.testsAlias), "routes/morse-code-tests.tsx"),
  route(routeSlug(ROUTES.testOnlineAlias), "routes/morse-code-test-online.tsx"),
  route(routeSlug(ROUTES.morseReaderAlias), "routes/morse-reader.tsx"),
  route(routeSlug(ROUTES.readMorseAlias), "routes/read-morse-code.tsx"),
  route(routeSlug(ROUTES.morseToEnglishAlias), "routes/morse-to-english.tsx"),
  route(routeSlug(ROUTES.morseCodeToEnglishAlias), "routes/morse-code-to-english.tsx"),
  route(routeSlug(ROUTES.textToMorseMp3Alias), "routes/text-to-morse-code-mp3.tsx"),
  route(routeSlug(ROUTES.morseToMp3Alias), "routes/morse-to-mp3.tsx"),
  route(routeSlug(ROUTES.morseCodeToMp3Alias), "routes/morse-code-to-mp3.tsx"),
  route(routeSlug(ROUTES.morseCodeMp3Alias), "routes/morse-code-mp3.tsx"),
  route(routeSlug(ROUTES.morseCodeAudioMp3Alias), "routes/morse-code-audio-mp3.tsx"),
  route(routeSlug(ROUTES.generatorMp3Alias), "routes/morse-code-generator-mp3.tsx"),
  route(
    routeSlug(ROUTES.mp3GeneratorOnlineAlias),
    "routes/morse-code-mp3-generator-online.tsx",
  ),
  route(routeSlug(ROUTES.audioDownloadAlias), "routes/morse-code-audio-download.tsx"),
  route(routeSlug(ROUTES.downloadAudioAlias), "routes/morse-code-download-audio.tsx"),
  route(routeSlug(ROUTES.downloadMorseAudioAlias), "routes/download-morse-code-audio.tsx"),
  route(routeSlug(ROUTES.textToMorseMp3ShortAlias), "routes/text-to-morse-mp3.tsx"),
  route(routeSlug(ROUTES.translatorMp3Alias), "routes/morse-code-translator-mp3.tsx"),
  route(
    routeSlug(ROUTES.translatorAudioMp3Alias),
    "routes/morse-code-translator-audio-mp3.tsx",
  ),
  route(routeSlug(ROUTES.videoMakerAlias), "routes/morse-code-video-maker.tsx"),
  route(routeSlug(ROUTES.morseVideoGeneratorAlias), "routes/morse-video-generator.tsx"),
  route(routeSlug(ROUTES.videoCreatorAlias), "routes/morse-code-video-creator.tsx"),
  route(routeSlug(ROUTES.textToMorseVideoAlias), "routes/text-to-morse-code-video.tsx"),
  route(routeSlug(ROUTES.morseCodeToVideoAlias), "routes/morse-code-to-video.tsx"),
  route(routeSlug(ROUTES.videoTranslatorAlias), "routes/morse-code-video-translator.tsx"),
  route(routeSlug(ROUTES.videoMorseTranslatorAlias), "routes/video-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.translatorVideoAlias), "routes/morse-code-translator-video.tsx"),
  route(routeSlug(ROUTES.videoToTextAlias), "routes/morse-code-video-to-text.tsx"),
  route(
    routeSlug(ROUTES.translatorVideoToTextAlias),
    "routes/morse-code-translator-video-to-text.tsx",
  ),
  route(
    routeSlug(ROUTES.fromVideoTranslatorAlias),
    "routes/morse-code-from-video-translator.tsx",
  ),
  route(routeSlug(ROUTES.translateFromVideoAlias), "routes/translate-morse-code-from-video.tsx"),
  route(routeSlug(ROUTES.mp4ToMorseTranslatorAlias), "routes/mp4-to-morse-code-translator.tsx"),
  route(routeSlug(ROUTES.videoToMorseAlias), "routes/video-to-morse-code.tsx"),
  route(
    routeSlug(ROUTES.videoToMorseTranslatorAlias),
    "routes/video-to-morse-code-translator.tsx",
  ),
  route(routeSlug(ROUTES.ebookTranslatorAlias), "routes/morse-code-ebook-translator.tsx"),

  // Misc / legal
  route("misc", "routes/misc/misc.tsx", [
    route("cookies-policy", "routes/misc/misc.cookies-policy.tsx"),
    route("privacy-policy", "routes/misc/misc.privacy-policy.tsx"),
    route("socials", "routes/misc/misc.socials.tsx"),
    route("terms-of-service", "routes/misc/misc.terms-of-service.tsx"),
  ]),
] satisfies RouteConfig;
