export {
  MORSE_VIDEO_BACKGROUND_LABELS as BOOK_VIDEO_BACKGROUND_LABELS,
  MORSE_VIDEO_INTENSITY_LABELS as BOOK_VIDEO_INTENSITY_LABELS,
  MORSE_VIDEO_RESOLUTION_LABELS as BOOK_VIDEO_RESOLUTION_LABELS,
  MORSE_VIDEO_TEXT_DISPLAY_LABELS as BOOK_VIDEO_TEXT_DISPLAY_LABELS,
  MORSE_VIDEO_VISUAL_STYLE_DETAILS as BOOK_VIDEO_VISUAL_STYLE_DETAILS,
  describeMorseVideoSettings as describeBookVideoSettings,
} from "~/client/components/shared/video/morseVideoPresets";
